### ISSUE TITLE
No way to disable SVGO

### ISSUE THREAD

**Issue by coreyward** [zabute/gatsby-plugin-svgr#10]
Doesn't seem like `svgo: false` in the options works. Unfortunately SVGO is causing me some issues with inlined SVGs and I'd like to disable to confirm. 

I'd fix, but I know very little about node packages or how webpack works.

**Comment by zabute** [comment]
I wasn't able to reproduce this on a fresh project with the default starter. If you could upload a repo that can reproduce this, It would help a lot.

**Comment by zabute** [comment]
@coreyward did you figure this out yet?

**Comment by coreyward** [comment]
No, I wound up using the URL version (which means I can't style via CSS) to avoid issues with conflicting IDs (thanks to the way SVGO “optimizes” those references).

**Comment by jhoffmcd** [comment]
I know this has been a closed issue for a long time, but I'm trying to adjust the SVGO config myself now and it doesn't seem like the options are getting passed to `svgr`. I can try and take a look at this and test.

**Comment by coreyward** [comment]
@jhoffmcd Please open a new issue and share your configuration. This issue refers to a previous version and the plugin has been rebuilt significantly since this was opened.
