### ISSUE TITLE
How to import icons using the sprite SVG icon file method?

### ISSUE THREAD

**Issue by nimaiwalsh** [zabute/gatsby-plugin-svgr#11]
Hi guys,

Great work on the plugin. Does any one know how to import individual icons using the SVG sprite method (As seen here: [https://css-tricks.com/svg-sprites-use-better-icon-fonts/](https://css-tricks.com/svg-sprites-use-better-icon-fonts/) using the `<use xlinkHref>` tag.

I tried but failed at implementing this method.

**Comment by dustinhorton** [comment]
@nimaiwalsh This is a plugin for using [SVGR](https://github.com/smooth-code/svgr) within Gatsby. SVGR is for transforming SVG files into React components, which is pretty different from using SVG sprites. Maybe check out this post: https://varun.ca/icon-component/

**Comment by nimaiwalsh** [comment]
@dustinhorton thanks for the clarification and link to the awesome article.
