### ISSUE TITLE
Unable to find plugin "gatsby-plugin-svgr"

### ISSUE THREAD

**Issue by tedcm** [zabute/gatsby-plugin-svgr#15]
It says unable to find plugin "gatsby-plugin-svgr" on the gatsby-starter-hero-blog.

**Comment by dustinhorton** [comment]
@tedcm Looks like someone just opened an issue on that starter repo @ https://github.com/greglobinski/gatsby-starter-hero-blog/issues/5

**Comment by tedcm** [comment]
Much appreciated sir. Thank you.
