### ISSUE TITLE
Gatsby v2 compat

### ISSUE THREAD

**Issue by seaneking** [zabute/gatsby-plugin-svgr#19]
Possibly related to  #17 (not that familiar with svgr itself), but `gatsby-plugin-svgr` completely breaks render in Gatsby 2, causing it to silently fail (took me aaages to figure out it was svgr going wrong).

Since it fails silently, can't be much help debugging, but I can only assume it's to do with Webpack 4, and that bumping to `@svgr/webpack` would fix it. 

Could we try that and release under a `next` tag for Gatsby v2? Seems to solve both issues, don't have to worry about breaking gatsby/webpack 1, keeps compat going forward for Gatsby 2

**Comment by seaneking** [comment]
Just saw #14 and #18 – any plans to merge one of these?

**Comment by seaneking** [comment]
Any update on this? Using #21 in prod ([here](https://littleplanetcreative.com)). Would be great to get it merged to mainline

**Comment by zabute** [comment]
#21 is now published. You can install it using the `@next` tag. Sorry for the long delay.

**Comment by seaneking** [comment]
Thanks! I'll close this issue since that resolves v2 compat.
