### ISSUE TITLE
Part of SVG not visible

### ISSUE THREAD

**Issue by cardiv** [zabute/gatsby-plugin-svgr#22]
Using Gatsby v2 and installed plugin with `@next` flag.

Part of my SVG is not visible with option `icon: true`.

<img width="56" alt="icon" src="https://user-images.githubusercontent.com/43521823/46255255-343a2180-c49b-11e8-858d-9cd7e3228ce6.png">

Furthermore: Is `viewBox` an actual option of _svgr_? I don't see this option there and do not recognize any difference in setting it to `true`, `false` or leaving it off.

**Comment by centrical** [comment]
I experience the same thing. I upgraded to Gatsby v2 and now the plugin doesn't always respect its own options. In my case, it's "viewbox: true". Omitting this settings lets the SVG scale out of its container. The strange thing is that it does not happen always.

**Comment by centrical** [comment]
I have found a fix. For some reason, in this V2-compatible version, the plugin gets confused if your SVGs contain a dimension definition using pixels - and not points.  If I use 'pt' instead of 'px' in the width and height attributes, everything works like normal again.

**Comment by coreyward** [comment]
@cardiv You probably want to use `viewBox` instead of `viewbox` (note the camelCasing).

**Comment by cardiv** [comment]
@coreyward Sorry, that was a typo. I copied `gatsby-config.js` from the readme of this repo. What should that option do?

@centrical The `width` and `height` attributes of the `svg` element do not contain any values in my files, only integers.

But it doesn't matter anyway, since the `icon` option converts them to `1em`. With `icon` set to `false`, it works. But they do not scale with `font-size`.

**Comment by coreyward** [comment]
Oh sorry, I thought you meant in your SVG file. 

As for resolving this, I actually disable `svgo` entirely. It's not designed to be automated or work with multiple files, so it has a few routines that interfere with the correct rendering of SVGs when inlined into an HTML page (which is what `svgr` enables).

This is how you can run with svgo disabled:

    {
      resolve: "gatsby-plugin-svgr",
      options: {
        svgo: false,
      },
    }

**Comment by zabute** [comment]
> ... don't understand what the viewBox option of this plugin does. Any explanation?

 If `viewBox` is set to false, `svgo` will remove the`viewBox` attribute from the svg. But  it will only do so if the width and height attributes are equal and are identical to the width and height specified inside the `viewBox` attribute.

**Comment by cardiv** [comment]
@coreyward Thanks for the hint, if I run into any issues I will try that.

@zabute Hm, I tested a bit. My svg: `width=24`, `height=24` and `viewBox="0 0 24 24"`.

Option `icon` set to `true` and `viewBox` gets rendered no matter what value the **option** `viewBox` has. Now that makes sense, since `icon` converts the `width` and `height` values to `1em`.

But if `icon` is set to `false`, the `viewBox` attribute gets never rendered, even when `viewBox` **option** is set to `true`.

**Comment by coreyward** [comment]
Closing this for now; if you still need help or believe there's a bug in gatsby-plugin-svgr let us know.
