### ISSUE TITLE
How to replace attributes?

### ISSUE THREAD

**Issue by ng-hai** [zabute/gatsby-plugin-svgr#23]
I have used this plugin successfully for SVG to React Component, but I get some struggle to figure out how to replace `fill` attribute. This is my configuration

```js
    {
      resolve: 'gatsby-plugin-svgr',
      options: {
        icon: true,
        viewBox: false,
        expandProps: 'end',
        replaceAttrValues: {
          '#FFBB00': 'currentColor',
        },
      },
    },
```

It didn't work as expected

**Comment by ng-hai** [comment]
Turn out SVGR treat color with six-digit form as three-digit form. Weird 🤔

**Comment by ng-hai** [comment]
Oops, I forgot this issue. I got some trouble yesterday with `gatsby-plugin-svgr@2.0.0`. I don't know why Gatsby always complain that `Module cannot be parsed` for each svg file when building for production. So I have to go back with `@svgr/cli` to meet the deadline.

**Comment by dioptre** [comment]
Does this work? I tried it in the latest build and can't get the colors working...
