### ISSUE TITLE
2.0.0 breaks png imports

### ISSUE THREAD

**Issue by seaneking** [zabute/gatsby-plugin-svgr#30]
Not sure exactly what changed between `2.0.0-alpha` (which was working great for me) and `2.0.0` mainline, but I just updated and installed `@svgr/webpack` as a peer dep, and now Gatsby is complaining about imported PNG images and missing a relevant loader. Any ideas what could be causing this? It's definitely `plugin-svgr` that's doing it — does it mess with the default file/url loaders in Gatsby?

**Comment by zabute** [comment]
> does it mess with the default file/url loaders in Gatsby?

Yes, we have to rewire the default image asset loader configs to be able to use svgr. It looks like I messed up when trying to use Rule.issuer to filter out non-javascript issuers. Will fix this asap.

**Comment by zabute** [comment]
Should be fixed `2.0.1` Please confirm

**Comment by lablancas** [comment]
This seems to be working now
