### ISSUE TITLE
View Box not preserved in React Component

### ISSUE THREAD

**Issue by lablancas** [zabute/gatsby-plugin-svgr#32]
My SVG file has a `viewBox` defined, but the React Component created does not include the `viewBox` even when I define `viewBox: true` in my `gatsby-config.js`. This is causing the SVG to not scale properly. If I import the data uri and render in an image tag, it works.

**Comment by coreyward** [comment]
`viewBox` is not a valid SVGR configuration flag.

**Comment by lablancas** [comment]
For reference, my imported SVG has height, width, and viewBox configured. Removing height and width fixed the issue for me.
