### ISSUE TITLE
Error running `gatsby develop` with v2.0.0 and v2.0.1

### ISSUE THREAD

**Issue by ooloth** [zabute/gatsby-plugin-svgr#33]
Thanks for this plugin!

`v2.0.0-alpha` is still working great, but running `gatsby develop` in Gatsby `v2.0.50` using either `v2.0.0` or `v.2.0.1` fails with the following error:

```sh
Plugin gatsby-plugin-svgr returned an error
Error: Cannot find module '@svgr/webpack'
```

The plugin still works if I roll back to `v2.0.0-alpha`, but I thought you'd probably want to know about this.

**Comment by zabute** [comment]
svgr is a peer dependency as of `2.0.0`.  You should install `@svgr/webpack` along with this plugin.
