### ISSUE TITLE
Upgrade to @svgr/webpack v4.x

### ISSUE THREAD

**Issue by Undistraction** [zabute/gatsby-plugin-svgr#36]
The plugin doesn't currently work correctly with the latest version of @svgr/webpack. Config settings defined within the plugin are not passed on to svgo.

Please upgrade the version of @svgr/webpack used.

**Comment by coreyward** [comment]
@Undistraction Can you provide more details (which settings aren't passed, what the configuration looks like, and which version of SVGR you're using) or a reproduction?

**Comment by elie222** [comment]
Could this be related to this issue?

https://github.com/gatsbyjs/gatsby/issues/12561

**Comment by coreyward** [comment]
@elie222 No, this seems unrelated, and likely not actually a bug but a misconfiguration or misunderstanding (svgr options are not all passed to svgo, for example).
