### ISSUE TITLE
Error rendering the svg

### ISSUE THREAD

**Issue by jonniebigodes** [zabute/gatsby-plugin-svgr#37]
While working on solving a  issue, namely this [one](https://github.com/gatsbyjs/gatsby/issues/12561), which uses this plugin and storybook, i implemented a simple gatsby website using typescript, a simple hello world one, without any "bells and whistles"(pardon the bad pun), to test out what could be the root of the issue linked above. I was able to solve that issue and got it to work as you can see my latest comment. But it led me to the reason of this specific issue.

I installed the plugin and followed the instructions to add the plugin to gatsby website. To be safe i kept it simple. All went fine and i was able to make the plugin work with storybook. The issue is when i start gatsby, issuing `gatsby develop` goes without any problems. It's when i open a page that the following error pops up:
![gatsby_plugin_svgr_error](https://user-images.githubusercontent.com/22988955/54780166-faa7cf00-4c10-11e9-9fae-8089ad75e10d.png)

Here are the relevant parts:
- Package.json dependencies:
```json
{
  
  "dependencies": {
    "@svgr/webpack": "^4.1.0",
    "gatsby": "^2.1.20",
    "gatsby-plugin-sass": "^2.0.10",
    "gatsby-plugin-svgr": "^2.0.2",
    "gatsby-plugin-typescript": "^2.0.10",
    "node-sass": "^4.11.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "typescript": "^3.3.3333",
    "webpack": "^4.29.6"
  },
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@types/node": "^11.11.4",
    "@types/react": "^16.8.8",
    "@types/react-dom": "^16.8.2",
    "@typescript-eslint/eslint-plugin": "^1.4.2",
    "@typescript-eslint/parser": "^1.4.2",
    "babel-loader": "^8.0.5",
    "gatsby-plugin-tslint": "^0.0.1",
    "tslint": "^5.13.1",
    "tslint-loader": "^3.5.4",
    "tslint-react": "^3.6.0",
    "@storybook/react": "^5.0.3",
    "@storybook/addon-actions": "^5.0.3",
    "@storybook/addon-links": "^5.0.3",
    "@storybook/addons": "^5.0.3"
  },
  "engines": {
    "node": ">=8.0.0"
  }
}
```

- `gatsby-config.js` contents:
```javascript
module.exports = {
  siteMetadata: {
    name: `Hello Typescript World!`,
    tagline: `Gatsby + SASS + Typescript = 💪`
  },  
  plugins: [
    `gatsby-plugin-sass`,
    `gatsby-plugin-typescript`,
    `gatsby-plugin-tslint`,
    {
      resolve:'gatsby-plugin-svgr',
      options: {
        icon: true,
      },
    }
  ],
}

```
- Component that imports the svg:
```typescript
import * as React from 'react';
import Star from '../assets/icons/Five-pointed_star.svg';
// import Star from './Five-pointed_star.svg';
const SimpleSvg: React.FunctionComponent = () => (
    <div style={{display: 'flex', justifyContent: 'space-around', maxWidth: `960px`, margin: `1.45rem` }}>
        <div>
            <h4>this is a star injected directly into a react component</h4>
            <Star/>
        </div>
       {/*  <div>
            <h4>this is a star injected into a img element</h4>
            <img src={Star} alt="A five point star"/>
        </div> */}
    </div>
);
export default SimpleSvg;
```
- The contents of the the svg, it's reather simple, it was used for teting purposes.
```xml
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="255" height="240" viewBox="0 0 51 48">
<title>Five Pointed Star</title>
<path fill="none" stroke="#000" d="m25,1 6,17h18l-14,11 5,17-15-10-15,10 5-17-14-11h18z"/>
</svg>
```

With a little tweak on storybook, it works without any issues. But not with gatsby. Any ideas on to solve this issue? Is there anything missing in my end? Some configuration or something else?

The full code is [here](https://github.com/jonniebigodes/test_gatsby_svgr_storybook)

Feel free to provide feedback. Thanks in advance

**Comment by coreyward** [comment]
The error you're experiencing is telling you that `Star` isn't a valid React component, and it's right: the default import from an `svg` file is the source, per the default loader. SVGR provides an additional named export (`ReactComponent`). All this plugin does is augment the webpack configuration to add SVGR to the loaders. 

You can do either of the following:

```jsx
import { ReactComponent as Star } from "star.svg"

export default () => (
  <div>
    <Star />
  </div>
)
```
…or…
```jsx
import star from "star.svg"

export default () => (
  <div>
    <img src={star} alt="A star" />
  </div>
)
```

If you need to import both the source and the component, you can do that as well, but you'll be including the data twice, which isn't ideal.

**Comment by jonniebigodes** [comment]
@coreyward you're right...after a couple of tests i saw the error of my ways. Forgot that this is Gatsby not the storybook environment. To make it run with storybook the import way is correct. But for Gatsby it's like you said. Once again sorry for the epic facepalm

**Comment by busticated** [comment]
@coreyward @zabute is this a somewhat new change? i ask b/c running under Gatsby v1 and using `gatsby-plugin-svgr@0.2.1`, my app used imports like:

```
import Foo from 'path/to/Foo.svg';
```

...and everything worked as expected.

now that i'm upgrading to Gatsby v2 and using `gatsby-plugin-svgr@2.0.2`, i'm having to use the `import { ReactComponent as Foo } from 'path/to/Foo.svg';` form and it's proving to be fairly disruptive. i see there's a `template` option - perhaps that can be leveraged to reestablish the original export behavior?
