### ISSUE TITLE
Allow Disabling of SVGO Plugins

### ISSUE THREAD

**Issue by Undistraction** [zabute/gatsby-plugin-svgr#42]
Currently you offer a `plugins` object to pass plugin configuration to SVGO, however this doesn't allow plugins to be disabled, only configured. 

SVGO [provides](https://github.com/svg/svgo#cli) a `disable` flag: `--disable=PLUGIN` or for multiple: `--disable=PLUGIN1,PLUGIN2` that allows disabling of plugins. 

Please provide a mechanism so that a list of plugins to be disabled can be passed through to SVGO. 

For example, currently it is impossible to disable `removeViewBox` which is necessary to enable `removeDimensions`. Setting `removeViewBox` to `false` isn't enough in this instance.

**Comment by coreyward** [comment]
@Undistraction This plugin isn't actually responsible for the `plugins` option; all options get passed straight through to [SVGR](https://github.com/smooth-code/svgr). 

https://github.com/zabute/gatsby-plugin-svgr/blob/5087926076e61a0d5681c842af42c73d55a89653/gatsby-node.js#L42-L45

**Comment by Undistraction** [comment]
@coreyward  Ah sorry. Libraries within libraries within libraries. So I could probably do this with a separate SVGO config file?

**Comment by coreyward** [comment]
@Undistraction Hahaha so true. I've worked on this plugin on and off for a year and I still confuse which of these similar names does what part. Turtles all the way down.

And yes, as I understand it, you can use a `.svgo.yml` file to configure SVGO and that will work with this plugin as well. It's unfortunate that SVGR doesn't accept a boolean to disable the SVGO plugins, though.

**Comment by Undistraction** [comment]
For anyone stumbling upon this, this approach does work. Copy the [.svgo.yaml](https://github.com/svg/svgo/blob/master/.svgo.yml) in the root of the SVGO's repo and remove any plugins you want to disable.
