### ISSUE TITLE
Dynamic importing of svgs?

### ISSUE THREAD

**Issue by jonny-harte** [zabute/gatsby-plugin-svgr#45]
Hi,

Is there anyway to dynamically import the svgs into a component? I've seen some examples of using React.lazy to import but I havent been able to get it to work.

Ideally Im looking for a react compoent where I can pass the filename of the svg as a prop.

https://www.digitalocean.com/community/tutorials/react-loading-components-dynamically-hooks#loading-components-on-demand

**Comment by coreyward** [comment]
I typically end up doing this manually ([example](https://github.com/coreyward/takeout-tracker-web/blob/9009ebe1566e2ab5a9b6b7dbea40b76630fc0e86/src/lib/icons.js)), but you might have some luck with something like [babel-plugin-wildcard](https://github.com/vihanb/babel-plugin-wildcard) if that works with your setup. 

I don't think there's anything specific to this plugin that would prevent what you're doing, right?

**Comment by zabute** [comment]
Hi @jonny-harte 

We can't use `React.Lazy` in Gatsby because its [not available for SSR](https://reactjs.org/docs/code-splitting.html#reactlazy) as of yet. You can use loadable-components as suggested by the React docs.

Or do this:

```JSX
// Svg.js
import { useEffect, useState } from "react"

export default function Svg({ path }) {
  const [svg, setSvg] = useState([])

  useEffect(() => {
    async function loadSvg() {
      const { ReactComponent } = await path
      setSvg(ReactComponent)
    }

    loadSvg()
  }, [path])

  return svg
}
```

Then in your pages:

```jsx 
<Svg path={import(/** path to svg file**/)} />
```

I hope this helps.

**Comment by zabute** [comment]
Did you get it working @jonny-harte ?. Closing because this is really not related to this project. Feel free to continue the discussion.

**Comment by leilahbirchall** [comment]
@jonny-harte interested to know if you found a solution for this?
