### ISSUE TITLE
Support filename pattern

### ISSUE THREAD

**Issue by tremby** [zabute/gatsby-plugin-svgr#7]
I'd find it more useful to process SVGs with a particular filename pattern and no others, rather than the current options, which are all-or-nothing, or "process only SVGs in this particular directory".

Please consider adding an option to provide a filename regex, such as `/\.inline\.svg$/`.

**Comment by zabute** [comment]
Sure. In retrospect, I should have just gone with passing ```include``` and ```exclude```  through to the loader.

**Comment by zabute** [comment]
Sorry for the long pause, @tremby.

Looks like svgr has added a feature that makes it even more flexible than sticking to a filename pattern or processing only a particular directory (see updated usage). I have removed the `dir` option in 1.0.0 in favor of it. Let me know if it doesn't cover your use case.

**Comment by xuopled** [comment]
I want the svg inside my "icons" folder have the `--icon` option but not all my SVGs. Is it possible?

**Comment by coreyward** [comment]
You can now use `include` and `exclude` options to specify which SVG files you would like to have processed by the svgr-loader. Additionally, the loader is skipped when referencing SVG files outside of your JS.
